apiVersion: apps/v1
kind: Deployment
metadata:
  name: slack-deployment
  labels:
    name: slack
spec:
  replicas: 1
  selector:
    matchLabels:
      name: slack
  strategy: {}
  template:
    metadata:
      labels:
        name: slack
    spec:
      containers:
      - env:
        - name: SLACK_BOT_NAME
          valueFrom:
            secretKeyRef:
              key: SLACK_BOT_NAME
              name: slackbot-secrets
        - name: SLACK_BOT_TOKEN
          valueFrom:
            secretKeyRef:
              key: SLACK_BOT_TOKEN
              name: slackbot-secrets
        image: staticdev/k8s-python-slackbot:0.0.3
        name: slack
        resources: {}
      restartPolicy: Always
status: {}